### ISSUE TITLE
Wrong score value

### ISSUE THREAD

**Issue by MarcusAldrey** [ForceTower/UEFS_Sagres_App#2]
In the initial screen of the application my score is shown as 3. That's MUST to be a mistake.

**Comment by ForceTower** [comment]
Hm.. The engineers are going to take a look at your problem. Sorry for the inconvenience

**Comment by ForceTower** [comment]
After a long analysis, we believe we found the source of the bug that causes the problem. A new version is going to be released next week. With a large variety of improvements, yours included
