### ISSUE TITLE
Sometimes the grades page doesn't have the div[boletins]

### ISSUE THREAD

**Issue by ForceTower** [ForceTower/UEFS_Sagres_App#7]
https://github.com/ForceTower/UEFS_Sagres_App/blob/ebce878c67cf7cd6a361e76183bc4231799dcee7/app/src/main/java/com/forcetower/uefs/sagres_sdk/parsers/SagresGradesParser.java#L89

**Comment by ForceTower** [comment]
Caused when the page sent is not a grades page... when sagres just disconnects you for no reason.
Anyway, fixed...
But the grades will not update on this call

**Comment by Keader** [comment]
still dont understand why you write it in english :)

**Comment by ForceTower** [comment]
Because it's fun

**Comment by Keader** [comment]
![adesivo_autismo](https://user-images.githubusercontent.com/7120913/34084333-488ddcac-e365-11e7-8a46-6171c1fe4702.jpg)

**Comment by ForceTower** [comment]
🙃
