### ISSUE TITLE
ToDo List (Nova Feature)

### ISSUE THREAD

**Issue by Keader** [ForceTower/UEFS_Sagres_App#8]
- Adicionar a opção de criar TODOLIST, para que os usuários consigam se organizar...
adicionar a opção de colocar data de entrega, com alerta de quando estiver chegando próximo da data de entrega e não estiver feito tipo: "Eita cuzão, já é para entregar amanha e tu não fez nada ainda, ta fudido parça."

Pode ser 1 por matéria ou 1 geral, wherever
Porem tem que ser por checkbox, porque checkbox > all

Estilo:

- [x] Essa feature é 10/10
- [x] Todos amam checkbox
- [ ] yay, pararei de fazer isso pelo gist \o/

**Comment by Keader** [comment]
still waiting motherfucker

**Comment by ForceTower** [comment]
Relax... Kkkkk

**Comment by ForceTower** [comment]
A feature será incluída na próxima atualização :)
O código dela já está praticamente todo escrito, falta somente uma coisa para deixar a interface mais bonita
